name: Linux

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@v1.5.2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test